insert into buku (isbn, judul, penulis, penerbit) values ('902061897-0', 'EOR', 'Christophe Khosa', 'Lynch-Champlin');
insert into buku (isbn, judul, penulis, penerbit) values ('772523057-2', 'Oil on Canvas', 'Sadie Wyeld', 'Halvorson-Funk');
insert into buku (isbn, judul, penulis, penerbit) values ('103012228-8', 'WTT', 'Anstice Roches', 'Johns-Streich');
insert into buku (isbn, judul, penulis, penerbit) values ('942998406-3', 'BTS Installation', 'Carolus Redfern', 'Sawayn, Bosco and Reynolds');
insert into buku (isbn, judul, penulis, penerbit) values ('594544581-9', 'Signal Processing', 'Katy Lombard', 'Mante, Haley and Satterfield');
insert into buku (isbn, judul, penulis, penerbit) values ('516246245-4', 'QMF', 'Otho Well', 'Kshlerin-Lakin');
insert into buku (isbn, judul, penulis, penerbit) values ('666016747-1', 'WS', 'Frankie Lempke', 'Hills, Toy and Marquardt');
insert into buku (isbn, judul, penulis, penerbit) values ('202865395-7', 'Payroll', 'Alexine Overall', 'Rutherford Group');
insert into buku (isbn, judul, penulis, penerbit) values ('669329239-9', 'Business Process', 'Maxie Bootman', 'Prosacco LLC');
insert into buku (isbn, judul, penulis, penerbit) values ('971553748-0', 'Executive Coaching', 'Rhiamon Pestridge', 'Murazik Group');
insert into buku (isbn, judul, penulis, penerbit) values ('427356661-3', 'FDQM', 'Norah Boulsher', 'Bergstrom-Maggio');
insert into buku (isbn, judul, penulis, penerbit) values ('839904020-7', 'Sound', 'Ulric Ghiriardelli', 'Bruen-Collins');
insert into buku (isbn, judul, penulis, penerbit) values ('451286325-7', 'Digital TV', 'L;urette Blazic', 'Kautzer-Goldner');
insert into buku (isbn, judul, penulis, penerbit) values ('773543991-1', 'NIR Spectroscopy', 'Kathrine Horick', 'Beer-Murazik');
insert into buku (isbn, judul, penulis, penerbit) values ('595568360-7', 'Furniture', 'Giraud Burle', 'Schultz-Cummings');
insert into buku (isbn, judul, penulis, penerbit) values ('913371591-2', 'FP7', 'Nataniel Freathy', 'Bosco, Thiel and Nicolas');
insert into buku (isbn, judul, penulis, penerbit) values ('501865081-8', 'GST', 'Jeni Brend', 'McClure, Runte and Christiansen');
insert into buku (isbn, judul, penulis, penerbit) values ('206606522-6', 'LCD Projectors', 'Pavia Doylend', 'Gutmann, Runolfsson and Auer');
insert into buku (isbn, judul, penulis, penerbit) values ('185244478-9', 'Databases', 'Concettina Dearing', 'Predovic-Bruen');
insert into buku (isbn, judul, penulis, penerbit) values ('745309163-2', 'DBAccess', 'Lind Gors', 'Smitham LLC');
insert into buku (isbn, judul, penulis, penerbit) values ('367359607-1', 'IEEE 802.3', 'Debee Jakoubec', 'Von-Terry');
insert into buku (isbn, judul, penulis, penerbit) values ('101831786-4', 'Production Efficiency', 'Alys Szymanowski', 'Feest-Huel');
insert into buku (isbn, judul, penulis, penerbit) values ('949382805-0', 'EJB', 'Dorice Dwyr', 'Treutel, Bode and West');
insert into buku (isbn, judul, penulis, penerbit) values ('272481602-1', 'MDI', 'Guthrey Falloon', 'Runolfsdottir-Dare');
insert into buku (isbn, judul, penulis, penerbit) values ('225146735-1', 'MS Reporting Services', 'Mia Ousbie', 'Denesik-Langosh');
